name: Notifications

on: [push]

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_YUKI }}

jobs:
  notify-commit:
    runs-on: ubuntu-latest
    steps:
    - if: github.event == 'push'
      name: Notify commit (Discord)
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_USERNAME: Yuki @ Testing
      with:
        args: |
          New commits have been pushed to `{{ EVENT_PAYLOAD.repository.full_name }}`!
          {{ EVENT_PAYLOAD.commits.map(e => '- ' + e.message + ' by ' + e.author.name + ' (' + e.url + ')').join('\n') }}
